stations_data = {
	"East West":[
		("EW 1","Pasir Ris"),
		("EW 2","Tampines"),
		("EW 3","Simei"),
		("EW 4","Tanah Merah"),
		("EW 5","Bedok"),
		("EW 6","Kembangan"),
		("EW 7","Eunos"),
		("EW 8","Paya Lebar"),
		("EW 9","Aljunied"),
		("EW 10","Kallang"),
		("EW 11","Lavender"),
		("EW 12","Bugis"),
		("EW 13","City Hall"),
		("EW 14","Raffles Place"),
		("EW 15","Tanjong Pagar"),
		("EW 16","Outram Park"),
		("EW 17","Tiong Bahru"),
		("EW 18","Redhill"),
		("EW 19","Queenstown"),
		("EW 20","Commonwealth"),
		("EW 21","Buona Vista"),
		("EW 22","Dover"),
		("EW 23","Clementi"),
		("EW 24","Jurong East"),
		("EW 25","Chinese Garden"),
		("EW 26","Lakeside"),
		("EW 27","Boon Lay"),
		("EW 28","Pioneer"),
		("EW 29","Joo Koon"),
		("EW 30","Gul Circle"),
		("EW 31","Tuas Cresent"),
		("EW 32","Tuas West Road"),
		("EW 33","Tuas Link"),
	],
	"Changi":[
		("CG 1","Changi Airport"),
		("CG 2","Expo"),
		("CG 3","Tanah Merah")
	],
	'North South': [
        ('NS1', 'Jurong East'),
        ('NS2', 'Bukit Batok'),
        ('NS3', 'Bukit Gombak'),
        ('NS4', 'Choa Chu Kang'),
        ('NS5', 'Yew Tee'),
        ('NS7', 'Kranji'),
        ('NS9', 'Woodlands'),
        ('NS10', 'Admiralty'),
        ('NS11', 'Sembawang'),
        ('NS12', 'Canberra'),
        ('NS13', 'Yishun'),
        ('NS14', 'Khatib'),
        ('NS15', 'Yio Chu Kang'),
        ('NS16', 'Ang Mo Kio'),
        ('NS17', 'Bishan'),
        ('NS18', 'Braddell'),
        ('NS19', 'Toa Payoh'),
        ('NS20', 'Novena'),
        ('NS21', 'Newton'),
        ('NS22', 'Orchard'),
        ('NS23', 'Somerset'),
        ('NS24', 'Dhoby Ghaut'),
        ('NS25', 'City Hall'),
        ('NS26', 'Raffles Place'),
        ('NS27', 'Marina Bay'),
        ('NS28', 'Marina South Pier')
    ],
    'North East': [
        ('NE1', 'HarbourFront'),
        ('NE3', 'Outram Park'),
        ('NE4', 'Chinatown'),
        ('NE5', 'Clarke Quay'),
        ('NE6', 'Dhoby Ghaut'),
        ('NE7', 'Little India'),
        ('NE8', 'Farrer Park'),
        ('NE9', 'Boon Keng'),
        ('NE10', 'Potong Pasir'),
        ('NE11', 'Woodleigh'),
        ('NE12', 'Serangoon'),
        ('NE13', 'Kovan'),
        ('NE14', 'Hougang'),
        ('NE15', 'Buangkok'),
        ('NE16', 'Sengkang'),
        ('NE17', 'Punggol')
    ],
    'Circle': [
        ('CC1', 'Dhoby Ghaut'),
        ('CC2', 'Bras Basah'),
        ('CC3', 'Esplanade'),
        ('CC4', 'Promenade'),
        ('CC5', 'Nicoll Highway'),
        ('CC6', 'Stadium'),
        ('CC7', 'Mountbatten'),
        ('CC8', 'Dakota'),
        ('CC9', 'Paya Lebar'),
        ('CC10', 'MacPherson'),
        ('CC11', 'Tai Seng'),
        ('CC12', 'Bartley'),
        ('CC13', 'Serangoon'),
        ('CC14', 'Lorong Chuan'),
        ('CC15', 'Bishan'),
        ('CC16', 'Marymount'),
        ('CC17', 'Caldecott'),
        ('CC19', 'Botanic Gardens'),
        ('CC20', 'Farrer Road'),
        ('CC21', 'Holland Village'),
        ('CC22', 'Buona Vista'),
        ('CC23', 'one-north'),
        ('CC24', 'Kent Ridge'),
        ('CC25', 'Haw Par Villa'),
        ('CC26', 'Pasir Panjang'),
        ('CC27', 'Labrador Park'),
        ('CC28', 'Telok Blangah'),
        ('CC29', 'HarbourFront'),
        ('CE1', 'Bayfront'),
        ('CE2', 'Marina Bay')
    ],
    'Downtown Line': [
        ('DT1', 'Bukit Panjang'),
        ('DT2', 'Cashew'),
        ('DT3', 'Hillview'),
        ('DT5', 'Beauty World'),
        ('DT6', 'King Albert Park'),
        ('DT7', 'Sixth Avenue'),
        ('DT8', 'Tan Kah Kee'),
        ('DT9', 'Botanic Gardens'),
        ('DT10', 'Stevens'),
        ('DT11', 'Newton'),
        ('DT12', 'Little India'),
        ('DT13', 'Rochor'),
        ('DT14', 'Bugis'),
        ('DT15', 'Promenade'),
        ('DT16', 'Bayfront'),
        ('DT17', 'Downtown'),
        ('DT18', 'Telok Ayer'),
        ('DT19', 'Chinatown'),
        ('DT20', 'Fort Canning'),
        ('DT21', 'Bencoolen'),
        ('DT22', 'Jalan Besar'),
        ('DT23', 'Bendemeer'),
        ('DT24', 'Geylang Bahru'),
        ('DT25', 'Mattar'),
        ('DT26', 'MacPherson'),
        ('DT27', 'Ubi'),
        ('DT28', 'Kaki Bukit'),
        ('DT29', 'Bedok North'),
        ('DT30', 'Bedok Reservoir'),
        ('DT31', 'Tampines West'),
        ('DT32', 'Tampines East'),
        ('DT33', 'Upper Changi'),
        ('DT34', 'Expo')
    ],
    'Thomson-East Coast Line': [
        ('TE1', 'Woodlands North'),
        ('TE2', 'Woodlands'),
        ('TE3', 'Woodlands South')
    ]
}